#!/usr/bin/perl

use strict;
use warnings;
use Data::Random qw(:all);

use DBIx::DWIW;

sub get_data_for_field;

my ($database,$table,$outfile,$count) = ("test","jos_plugins","/tmp/ins.sql",3);
my $db = DBIx::DWIW->Connect(DB => $database,
			     User => 'root',
			     Host => undef,
			     Pass => ""
			    );
my $gendata_dispatch_table = {
			      "int" => \&generate_int,
			      "tinyint"  => \&generate_int,
			      "varchar"  => \&generate_varchar,
			      "char"  => \&generate_varchar,
			      "datetime" =>\&generate_datetime,
			      "date"  =>\&generate_datetime,
			      "timestamp" => \&generate_datetime
			     };
  
my @records = $db->Hashes("desc $table");
my $insert_sql = "INSERT IGNORE INTO $table VALUES";    
for (my $i=0;$i<$count;$i++)
  {
    $insert_sql .= "(";
    foreach my $rec (@records) {
      my $val = get_data_for_field($rec->{Type});
      $insert_sql .= "$val,";
    }
    $insert_sql =~ s/,$//g;
    $insert_sql .= "),\n";
  }

$insert_sql =~ s/,$//g;
open FH,">",$outfile;
print FH $insert_sql;

sub get_data_for_field
  {
  my $db_type = shift;
  my ($type,$type_args);
  
  if ($db_type =~ m/(\w+)(\((.*)\))?/) {
  $type = $1;
  $type_args = $3 if (defined($3)) ;
  if (exists $gendata_dispatch_table->{$type}) { 
    my $x = $gendata_dispatch_table->{$type}->($type,$type_args);
    return $x;
  }
  else {
    die "Don't know how to generate data for $type"
  }
}
  else {
    print "cannot parse $db_type";
  }
}

  
  sub generate_int
    {
      my $type = shift;
      my $n_digits = shift || 3;
      my $max = 10 ** $n_digits - 1 ; # $max is the maximum number
                                      # $n_digits long
      print "generating random number less than $max for $n_digits\n";
      return int(rand($max));
    }

    sub generate_varchar
      {
	my $type = shift;
	my $n_char = shift || 30;

	# the set "alphanumeric" contains a maximum og 62 characters.
	# If we pass the size parameter more than 62, we get a "size
	# value exceeds set size at /Library/Perl/5.8.8/Data/Random.pm
	# line 206" error
	if ($n_char<62) {
	  my @ranchar = rand_chars(set => "alphanumeric",size =>$n_char);
	  my $val = join "",@ranchar ;
	  my $x = '"'.$val.'"';
	  return $x;
	}
	else {
	  my $txt = generate_text("text",$n_char);
	  my $chars = substr $txt,0,$n_char;
	  my $quoted_chars = $chars.'"';
	  return $quoted_chars;
	}
      }

      sub generate_datetime
	{
	  my $type = shift;
	  my $randdatetime = rand_datetime(max => "now", min => '1978-9-21 00:00:00');
	  my $x = '"'. $randdatetime .'"';
	  return $x;
	}
	

	sub generate_text
	  {
	    my $type = shift;
	    my $n_words = shift || 100;
	    my @randwords = rand_words (size => $n_words);
	    my $val = join " ",@randwords;
	    my $x = '"'. $val .'"';
	    return $x;
	 }   


